FROM python:3.9-bullseye

USER root

# Specify versions of Firefox and geckodriver
ARG firefox_ver=135.0.1
ARG geckodriver_ver=0.36.0

# Update apt-get
RUN apt-get update

# Install dependencies for Firefox
RUN apt-get install -y --no-install-recommends --no-install-suggests \
  `apt-cache depends firefox-esr | awk '/Depends:/{print$2}'` \
  # additional 'firefox-esl' dependencies which are not in 'depends' list
  libasound2 libxt6 libxtst6

# Download and install Firefox
RUN curl -fL -o /tmp/firefox.tar.bz2 \
  https://ftp.mozilla.org/pub/firefox/releases/${firefox_ver}/linux-x86_64/en-GB/firefox-${firefox_ver}.tar.bz2 \
  && tar -xjf /tmp/firefox.tar.bz2 -C /tmp/ \
  && mv /tmp/firefox /opt/firefox \
  && ln -s /opt/firefox/firefox /usr/local/bin/firefox
 
# Download and install geckodriver
RUN curl -fL -o /tmp/geckodriver.tar.gz \
  https://github.com/mozilla/geckodriver/releases/download/v${geckodriver_ver}/geckodriver-v${geckodriver_ver}-linux64.tar.gz \
  && tar -xzf /tmp/geckodriver.tar.gz -C /tmp/ \
  && chmod +x /tmp/geckodriver \
  && mv /tmp/geckodriver /usr/local/bin/

# Cleanup unnecessary stuff
RUN apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
            $toolDeps \
 && rm -rf /var/lib/apt/lists/* \
           /tmp/*

# Run in headless mode
ENV MOZ_HEADLESS=1

# Upgrade pip and install selenium, requests, and pandas
RUN python3 -m pip install --upgrade pip && pip install selenium==4.* requests==2.* pandas==2.* --no-cache-dir 

# COPY and apply permissions to python script
COPY getdata.py ./
RUN chmod a+x /getdata.py

ENTRYPOINT ["python3", "./getdata.py"]