name: Build Processing Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'processing/**'
  pull_request:
    branches:
      - main
    paths:
      - 'processing/**'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for processing container
      id: meta-processing
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}/processing
        flavor: latest=false
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix=main-
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push processing container image
      uses: docker/build-push-action@v5
      with:
        context: ./processing
        file: ./processing/dockerfile
        push: true
        tags: ${{ steps.meta-processing.outputs.tags }}